services:
  aninsohbeti:
    build: .
    container_name: aninsohbeti
    restart: always
    ports:
      - "6000:6000"
    environment:
      - PORT=6000
      - NODE_ENV=production
      - TRUST_PROXY=true
      - TURNSTILE_SITE_KEY=0x4AAAAAAB4YbuB3ldcngp_X
      - TURNSTILE_SECRET_KEY=0x4AAAAAAB4YbtDAfAznXoaN5MfiETToWBU
