@echo off

:: ##########################################################################
::
::  Gradle startup script for Windows generated by Gradle.
::
:: ##########################################################################

if "%DEBUG%" == "" @echo off
set DIRNAME=%~dp0
if "%DIRNAME%" == "" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

set DEFAULT_JVM_OPTS=

set WRAPPER_JAR=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar
if not exist "%WRAPPER_JAR%" call :downloadWrapperJar
if not exist "%WRAPPER_JAR%" goto missingWrapper

goto init

:missingWrapper
echo.
echo ERROR: Could not find or download gradle-wrapper.jar in %APP_HOME%\gradle\wrapper.
exit /b 1

:downloadWrapperJar
if not exist "%APP_HOME%\gradle\wrapper" mkdir "%APP_HOME%\gradle\wrapper"
set PROPERTIES_FILE=%APP_HOME%\gradle\wrapper\gradle-wrapper.properties
powershell -NoLogo -NoProfile -Command "`
    $propsPath = [System.IO.Path]::GetFullPath('%PROPERTIES_FILE%');`
    $defaultVersion = '8.2';`
    $version = $defaultVersion;`
    if (Test-Path $propsPath) {`
        $content = Get-Content -Raw $propsPath;`
        if ($content) {`
            $match = [regex]::Match($content, 'gradle-([0-9][0-9\\.]*)');`
            if ($match.Success) { $version = $match.Groups[1].Value }`
        }`
    }`
    $url = "https://raw.githubusercontent.com/gradle/gradle/v$version/gradle/wrapper/gradle-wrapper.jar";`
    Write-Host "Downloading Gradle wrapper jar (v$version)...";`
    Invoke-WebRequest -Uri $url -OutFile ([System.IO.Path]::GetFullPath('%WRAPPER_JAR%')) -UseBasicParsing`
"  || exit /b 1
exit /b 0

:init
set CMD_LINE_ARGS=%*

set JAVA_EXE=
if defined JAVA_HOME goto findJavaFromJavaHome

set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if %ERRORLEVEL% == 0 goto execute

echo.
echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
echo.
echo Please set the JAVA_HOME variable in your environment to match the
 echo location of your Java installation.

exit /b 1

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%\bin\java.exe

if exist "%JAVA_EXE%" goto execute

echo.
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%
echo.
echo Please set the JAVA_HOME variable in your environment to match the
 echo location of your Java installation.

exit /b 1

:execute
set CLASSPATH=%WRAPPER_JAR%

"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %CMD_LINE_ARGS%

:exit
